#!/bin/zsh

cd ~/dotfiles
git pull origin
yes | cp ./i3/config ~/.i3/
yes | cp ./i3/i3status/config ~/.config/i3status/
yes | cp ./profile ~/
yes | mv ~/profile ~/.profile
yes | cp mimeapps.list ~/.config/
yes | cp ./i3/screenlayout/* ~/.screenlayout
yes | chmod +x ./i3/bin/paci
yes | chmod +x ./i3/bin/pacr
yes | chmod +x ./i3/bin/pacc
yes | chmod +x ./i3/bin/file_finder
yes | chmod +x ./i3/bin/web_search
yes | chmod +x ./i3/bin/window_select
yes | chmod +x ./i3/bin/monitor_layout
yes | chmod +x ./i3/bin/gitpush
yes | chmod +x ./i3/bin/todo
